# (Part 7)

### prelims

In [1]:
import pandas as pd
import os

In [2]:
os.getcwd()

'C:\\Users\\Joshua\\Desktop\\PERSONAL\\Joshua Harvey\\education\\youtube\\Corey Schafer\\Python Tutorials'

In [3]:
os.chdir('C:\\Users\\Joshua\\Desktop\\PERSONAL\\Joshua Harvey\\education\\youtube\\Corey Schafer\\Python Tutorials\\data')
df = pd.read_csv('survey_results_public.csv')

In [4]:
pd.set_option('display.max_columns',85)

In [5]:
df_cols = pd.DataFrame(df.columns)
# -- notice that column wasn't a string integer but an integer 
df_cols.rename(columns={0:'col_name'},inplace=True)

In [6]:
df_cols.head(25)

          col_name
0       Respondent
1       MainBranch
2         Hobbyist
3      OpenSourcer
4       OpenSource
5       Employment
6          Country
7          Student
8          EdLevel
9   UndergradMajor
10        EduOther
11         OrgSize
12         DevType
13       YearsCode
14      Age1stCode
15    YearsCodePro
16       CareerSat
17          JobSat
18        MgrIdiot
19        MgrMoney
20         MgrWant
21         JobSeek
22    LastHireDate
23         LastInt
24        FizzBuzz

### aggregating

In [7]:
df['ConvertedComp'].median()

57287.0

In [8]:
# -- looks for numeric values (integers) and runs the calculation
df.median()

Respondent       44442.0
CompTotal        62000.0
ConvertedComp    57287.0
WorkWeekHrs         40.0
CodeRevHrs           4.0
Age                 29.0
dtype: float64

In [9]:
df.describe()

,Respondent,CompTotal,ConvertedComp,WorkWeekHrs,CodeRevHrs,Age
count,88883.000000,5.594500e+04,5.582300e+04,64503.000000,49790.000000,79210.000000
mean,44442.000000,5.519014e+11,1.271107e+05,42.127197,5.084308,30.336699
std,25658.456325,7.331926e+13,2.841523e+05,37.287610,5.513931,9.178390
min,1.000000,0.000000e+00,0.000000e+00,1.000000,0.000000,1.000000
25%,22221.500000,2.000000e+04,2.577750e+04,40.000000,2.000000,24.000000
50%,44442.000000,6.200000e+04,5.728700e+04,40.000000,4.000000,29.000000
75%,66662.500000,1.200000e+05,1.000000e+05,44.750000,6.000000,35.000000
max,88883.000000,1.000000e+16,2.000000e+06,4850.000000,99.000000,99.000000

In [10]:
df['CompTotal'].describe()

count    5.594500e+04
mean     5.519014e+11
std      7.331926e+13
min      0.000000e+00
25%      2.000000e+04
50%      6.200000e+04
75%      1.200000e+05
max      1.000000e+16
Name: CompTotal, dtype: float64

In [13]:
df['Hobbyist'].value_counts()

Yes    71257
No     17626
Name: Hobbyist, dtype: int64

In [18]:
df['Country'].value_counts()

United States            20949
India                     9061
Germany                   5866
United Kingdom            5737
Canada                    3395
                         ...
Brunei Darussalam            1
Niger                        1
Sao Tome and Principe        1
Timor-Leste                  1
North Korea                  1
Name: Country, Length: 179, dtype: int64

In [19]:
df['Country'].value_counts(normalize=True)

United States            0.236042
India                    0.102095
Germany                  0.066095
United Kingdom           0.064642
Canada                   0.038253
                           ...
Brunei Darussalam        0.000011
Niger                    0.000011
Sao Tome and Principe    0.000011
Timor-Leste              0.000011
North Korea              0.000011
Name: Country, Length: 179, dtype: float64

In [21]:
grp_country = df.groupby(['Country'])

In [22]:
grp_country.get_group('United States')

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
12,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,10 to 19 employees,Data or business analyst;Database administrato...,17,11,8,Very satisfied,Very satisfied,NaN,NaN,NaN,I am not interested in new job opportunities,3-4 years ago,Complete a take-home project;Interview with pe...,Yes,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,90000.0,Yearly,90000.0,40.0,There is a schedule and/or spec (made by me or...,"Meetings;Non-work commitments (parenting, scho...",All or almost all the time (I'm full-time remote),Home,A little above average,"Yes, because I see value in code review",5.0,"No, but I think we should",Developers and management have nearly equal in...,I have a great deal of influence,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Rust...,Couchbase;DynamoDB;Firebase;MySQL,Firebase;MySQL;Redis,Android;AWS;Docker;IBM Cloud or Watson;iOS;Lin...,Android;AWS;Docker;IBM Cloud or Watson;Linux;S...,Angular/Angular.js;ASP.NET;Express;jQuery;Vue.js,Express;Vue.js,Node.js;Xamarin,Node.js;TensorFlow,Vim;Visual Studio;Visual Studio Code;Xcode,Windows,Development;Testing;Production,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Yes,Yes,Twitter,In real life (in person),Username,2011,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
21,22,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,Some college/university study without earning ...,NaN,Taken an online course in programming or softw...,"10,000 or more employees","Data or business analyst;Designer;Developer, b...",35,12,18,Slightly satisfied,Very dissatisfied,Somewhat confident,No,No,"I’m not actively looking, but I am open to new...",More than 4 years ago,Interview with people in senior / management r...,No,Industry that I'd be working in;Financial perf...,I had a negative experience or interaction at ...,USD,United States dollar,103000.0,Yearly,103000.0,40.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Meeting...,"Less than half the time, but at least one day ...",Home,Average,No,NaN,"No, but I think we should","The CTO, CIO, or other management purchase new...",I have little or no influence,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,Elasticsearch;MySQL;Oracle;Redis,Elasticsearch;MySQL;Oracle;Redis,Docker;Linux;Raspberry Pi;Windows,Docker;Linux;Raspberry Pi;Windows,Angular/Angular.js;Ruby on Rails,Angular/Angular.js;Ruby on Rails,Node.js,Node.js,Sublime Text;Visual Studio;Visual Studio Code,Windows,"Outside of work, for personal projects",Not at all,NaN,Yes,Yes,Yes,Instagram,Online,Username,I don't remember,Daily or almost daily,Find answers to specific questions,3-5 times per week,Stack Overflow was much faster,0-10 minutes,Yes,A few times per week,Yes,"No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,47.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
22,23,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",Taken an online course in programming or softw...,"10,000 or more employees","Developer, full-stack",3,19,1,Slightly satisfied,Slightly satisfied,Very confident,No,Not sure,"I’m not actively looking, but I am open to new...",Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,Opportunities for professional development;How...,I was preparing for a job search,USD,United States dollar,69000.0,Yearly,69000.0,40.0,There is a schedule and/or spec (made by me or...,Distracting work environment;Meetings;Non-work...,A few days each month,Office,Average,"Yes, because I see value in code review",8.0,"Yes, it's part of our process",Developers and management have nearly equal in...,I have little or no influence,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Pyth...,Bash/Shell/PowerShell;Go;HTML/CSS;Java;JavaScr...,Oracle;SQLite,Couchbase;DynamoDB;Elasticsearch;Firebase;Oracle,Docker;Google Cloud Platform,Docker;iOS;Slack,React.js;Ruby on Rails,Express;React.js;Ruby on Rails;Vue.js,NaN,React Native;TensorFlow,Visual Studio Code,MacOS,Development;Testing;Production,NaN,Useful for immutable record keeping outside of...,Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Multiple times per day,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, I've heard of them, but I am not part of a...","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,22.0,Man,No,Straight / Heterosexual,Black or of African descent,No,Appropriate in length,Easy
25,26,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,United States,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...","10,000 or more employees","Designer;Developer, back-end;Developer, deskto...",12,8,8,Very satisfied,Very satisfied,NaN,NaN,NaN,"I’m not actively looking, but I am open to new...",Less than a year ago,Interview with people in peer roles;Interview ...,No,Remote work options;Diversity of the company o...,I was preparing for a job search,USD,United States dollar,114000.0,Yearly,114000.0,40.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Meeting...,"Less than half the time, but at least one day ...",Home,Far above average,"Yes, because I see value in code review",2.0,"Yes, it's not part of our process but the deve...",Developers typically have the most influence o...,I have a great deal of influence,Bash/Shell/PowerShell;C++;C#;HTML/CSS;JavaScri...,C#;HTML/CSS;JavaScript;Objective-C;Ruby;SQL;Sw...,Microsoft SQL Server;MySQL;Redis;SQLite,Microsoft SQL Server;MySQL;Redis;SQLite,AWS;Docker;Linux;MacOS;Microsoft Azure;Windows...,Android;Docker;iOS;Linux;MacOS;Microsoft Azure...,Angular/Angular.js;ASP.NET;Drupal;Express;jQue...,Angular/Angular.js;ASP.NET,.NET;.NET Core;Node.js;Xamarin,.NET;.NET Core;Node.js,Notepad++;Sublime Text;Vim;Visual Studio;Xcode,MacOS,Development;Testing,Not at all,A passing fad,Yes,SIGH,Yes,I don't use social media,In real life (in person),Username,2008,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,NaN,34.0,Man,No,Gay or Lesbian,NaN,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88818,78292,NaN,No,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",United States,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","A health science (ex. nursing, pharmacy, radio...",Completed an industry certification program (e...,"Just me - I am a freelancer, sole proprietor, ...",Academic researcher,42,14,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C;Python,Bash/Shell/PowerShell;C;Python,SQLite,SQLite,Linux;Raspberry Pi;Other(s):,Linux;Raspberry Pi;Other(s):,NaN,NaN,Chef,NaN,Emacs;IPython / Jupyter,Linux-based,I do not use containers,NaN,Useful for immutable record keeping outside of...,No,Yes,Yes,I don't use social media,In real life (in person),NaN,2013,A few times per week,Find answers to specific questions,Less than once per week,The other resource was slightly faster,11-30 minutes,Not sure / can't remember,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","No, not really",Somewhat less welcome now than last year,NaN,60.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Neither easy nor difficult
88840,82717,NaN,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",United States,No,"Secondary school (e.g. American high school, G...",NaN,NaN,NaN,NaN,Less than 1 year,NaN,Less than 1 year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Android;Windows,Android;Microsoft Azure;Windows,NaN,NaN,NaN,NaN,NaN,MacOS,Testing,NaN,NaN,No,SIGH,Yes,Facebook,In real life (in person),Username,2018,Less than once per month or monthly,Find answers to specific questions,Less than once per week,NaN,60+ minutes,No,NaN,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...",Not sure,NaN,Industry news about technologies you're intere...,44.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Neither easy nor difficult
88844,83397,NaN,Yes,Less than once per year,NaN,"Not employed, but looking for work",United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,12,9,Less than 1 year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Python;SQL,C;C++;C#;Go;Java;JavaScript;Python;R;Ruby;SQL;...,NaN,NaN,Android;Arduino;Slack,Android;Arduino;Docker;iOS;Raspberry Pi;Slack,Flask,Django;Drupal;Flask;jQuery;React.js,NaN,Chef;Torch/PyTorch,Eclipse;IPython / Jupyter;Sublime Text,MacOS,I do not use containers,NaN,NaN,NaN,SIGH,Yes,NaN,NaN,Handle,I don't remember,A few times per week,Find answers to specific questions;Learn how t...,3-5 times per week,They were about the same,NaN,Not sure / can't remember,NaN,Yes,"No, and I don't know what those are","No, not at all",Just as welcome now as I felt last year,NaN,27.0,Woman,No,Bisexual,White or of European descent,No,Appropriate in length,Easy
88859,85642,NaN,No,Less than once per year,"OSS is, on average, of LOWER quality than prop...","Independent contractor, freelancer, or self-em...",United States,No,Associate degree,"Information systems, information technology, o...",Taken an online course in programming or softw...,"Just me - I am a freelancer, sole proprietor, ...",Designer;Marketing or sales professional,20,7,Less than 1 year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Go;HTML/CSS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Visual Studio Code,Windows,I do not use containers,NaN,Useful for immutable record keeping outside of...,No,SIGH,Yes,NaN,In real life (in person),Handle,2008,Less than once per month or monthly,Find answers to specific questions,Less than once per week,Stack Overflow was slightly faster,60+ minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not at all",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,34.0,"Non-binary, genderqueer, or gender non-conforming",NaN,Bisexual;Gay or Lesbian,White or of European descent,No,Appropriate in length,Easy
88877,88282,NaN,Yes,Once a month or more often,The quality of OSS and closed source software ...,"Not employed, but looking for work",United States,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",NaN,"Developer, back-end;Developer, desktop or ente...",38,10,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;Go;HTML/CSS;JavaScript;W...,Bash/Shell/PowerShell;C;Go;HTML/CSS;JavaScript...,NaN,NaN,Linux,Linux;Raspberry Pi,React.js,Vue.js,Node.js,Ansible,Vim,Linux-based,I do not use containers,NaN,An irresponsible use of resources,No,NaN,Yes,I don't use social media,In real life (in person),Username,I don't remember,A few times per month or weekly,Find answers to specific questions,1-2 times per week,They were about the same,NaN,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,NaN,NaN,Man,No,Straight / Heterosexual,NaN,No,Too short,Neither easy nor difficult

In [27]:
grp_country['SocialMedia'].value_counts().head(30)

Country      SocialMedia
Afghanistan  Facebook                    15
             YouTube                      9
             I don't use social media     6
             WhatsApp                     4
             Instagram                    1
             LinkedIn                     1
             Twitter                      1
Albania      WhatsApp                    18
             Facebook                    16
             Instagram                   13
             YouTube                     10
             Twitter                      8
             LinkedIn                     7
             Reddit                       6
             I don't use social media     4
             Snapchat                     1
             WeChat 微信                    1
Algeria      YouTube                     42
             Facebook                    41
             Twitter                     14
             LinkedIn                     9
             I don't use social media     7
             Instagram                    7
             Reddit                       2
             WhatsApp                     2
Andorra      Facebook                     2
             I don't use social media     2
             Reddit                       1
             Snapchat                     1
             YouTube                      1
Name: SocialMedia, dtype: int64

In [28]:
grp_country.get_group('Afghanistan')['SocialMedia'].value_counts()

Facebook                    15
YouTube                      9
I don't use social media     6
WhatsApp                     4
Twitter                      1
Instagram                    1
LinkedIn                     1
Name: SocialMedia, dtype: int64

In [30]:
# -- another way to think about grouping for a single country. Same as above

filt_cntry = df['Country'] == 'Afghanistan'
df.loc[filt_cntry]['SocialMedia'].value_counts()

Facebook                    15
YouTube                      9
I don't use social media     6
WhatsApp                     4
Twitter                      1
Instagram                    1
LinkedIn                     1
Name: SocialMedia, dtype: int64

In [44]:
# -- this is yet another way to specifiy the country from the index rows

grp_country['SocialMedia'].value_counts(normalize=True).loc['China']

SocialMedia
WeChat 微信                   0.670549
YouTube                     0.088186
Weibo 新浪微博                  0.069884
I don't use social media    0.044925
Twitter                     0.044925
Reddit                      0.019967
LinkedIn                    0.018303
Facebook                    0.013311
Instagram                   0.011647
Youku Tudou 优酷              0.011647
WhatsApp                    0.004992
VK ВКонта́кте               0.001664
Name: SocialMedia, dtype: float64

### Other basic statistic functions

In [48]:
# -- [series].isin(['ex1','ex2']) can't be used but .loc on index with a similar list can be 

grp_country['ConvertedComp'].median().loc[['Germany', 'India']]

Country
Germany    63016.0
India      10080.0
Name: ConvertedComp, dtype: float64

In [49]:
# -- .agg returns a dataframe not a series 

grp_country['ConvertedComp'].agg(['median', 'mean'])

                                        median           mean
Country
Afghanistan                             6222.0  101953.333333
Albania                                10818.0   21833.700000
Algeria                                 7878.0   34924.047619
Andorra                               160931.0  160931.000000
Angola                                  7764.0    7764.000000
...                                        ...            ...
Venezuela, Bolivarian Republic of...    6384.0   14581.627907
Viet Nam                               11892.0   17233.436782
Yemen                                  11940.0   16909.166667
Zambia                                  5040.0   10075.375000
Zimbabwe                               19200.0   34046.666667

[179 rows x 2 columns]

In [50]:
grp_country['ConvertedComp'].agg(['median', 'mean']).loc[['India','China']]

          median          mean
Country
India    10080.0  28057.664916
China    28464.0  57430.421053

In [92]:
# -- df['Country'] == 'India' should have been used in a variable but wasn't to observe 
# -- that .loc was not needed in this evaluation 

'India: ' + str(df[df['Country'] == 'India']['EdLevel'].str.contains('Master').sum())

'India: 1877'

In [94]:
# -- this throws an error b/c 'str' can't be used on 'SeriesGroupBy' objects

# grp_country2 = df.groupby(['Country'])
# grp_country2['EdLevel'].str.contains('Master').sum()

In [155]:
pd.set_option('display.max_rows',200)
grp_country2 = df.groupby(['Country'])['EdLevel']
df2 = pd.DataFrame(grp_country2.apply(lambda x: x.str.contains('Master').sum()))
df2.head(200).sort_values(by='Country', ascending=True)

                                           EdLevel
Country
Afghanistan                                      1
Albania                                         24
Algeria                                         58
Andorra                                          0
Angola                                           1
Antigua and Barbuda                              1
Argentina                                       55
Armenia                                         28
Australia                                      274
Austria                                        236
Azerbaijan                                       9
Bahamas                                          1
Bahrain                                          2
Bangladesh                                      68
Barbados                                         0
Belarus                                         46
Belgium                                        225
Belize                                           0
Benin                                            1
Bhutan                                           0
Bolivia                                          1
Bosnia and Herzegovina                          21
Botswana                                         0
Brazil                                         247
Brunei Darussalam                                0
Bulgaria                                       165
Burkina Faso                                     0
Burundi                                          0
Cambodia                                         3
Cameroon                                        10
Canada                                         475
Cape Verde                                       0
Chad                                             0
Chile                                           24
China                                          129
Colombia                                        36
Congo, Republic of the...                        0
Costa Rica                                       9
Croatia                                        107
Cuba                                             2
Cyprus                                          22
Czech Republic                                 279
Côte d'Ivoire                                   15
Democratic People's Republic of Korea            0
Democratic Republic of the Congo                 3
Denmark                                        193
Djibouti                                         1
Dominica                                         1
Dominican Republic                               5
Ecuador                                         17
Egypt                                            8
El Salvador                                      7
Estonia                                         47
Ethiopia                                         2
Fiji                                             1
Finland                                        157
France                                        1424
Gabon                                            0
Georgia                                         10
Germany                                       1744
Ghana                                            7
Greece                                         182
Guatemala                                        3
Guinea                                           2
Guyana                                           0
Haiti                                            0
Honduras                                         2
Hong Kong (S.A.R.)                              40
Hungary                                        134
Iceland                                          6
India                                         1877
Indonesia                                       33
Iran                                           195
Iraq                                             3
Ireland                                        120
Israel                                         116
Italy                                          360
Jamaica                                          4
Japan                                          114
Jordan                                           6
Kazakhstan                                      11
Kenya                                           10
Kuwait                                           2
Kyrgyzstan                                       5
Lao People's Democratic Republic                 1
Latvia                                          33
Lebanon                                         29
Lesotho                                          0
Liberia                                          0
Libyan Arab Jamahiriya                           1
Liechtenstein                                    0
Lithuania                                       58
Luxembourg                                      24
Madagascar                                      10
Malawi                                           0
Malaysia                                        31
Maldives                                         1
Mali                                             2
Malta                                           12
Mauritania                                       2
Mauritius                                        4
Mexico                                          75
Monaco                                           1
Mongolia                                         3
Montenegro                                       4
Morocco                                         42
Mozambique                                       2
Myanmar                                          3
Namibia                                          0
Nepal                                           10
Netherlands                                    452
New Zealand                                     67
Nicaragua                                        3
Niger                                            0
Nigeria                                         37
North Korea                                      0
Norway                                         206
Oman                                             4
Other Country (Not Listed Above)                19
Pakistan                                       135
Panama                                           4
Papua New Guinea                                 0
Paraguay                                         6
Peru                                             8
Philippines                                      9
Poland                                         716
Portugal                                       191
Qatar                                            2
Republic of Korea                                4
Republic of Moldova                             11
Romania                                        170
Russian Federation                             608
Rwanda                                           0
Saint Kitts and Nevis                            0
Saint Vincent and the Grenadines                 0
San Marino                                       0
Sao Tome and Principe                            0
Saudi Arabia                                    10
Senegal                                         10
Serbia                                          99
Seychelles                                       0
Sierra Leone                                     0
Singapore                                       63
Slovakia                                       105
Slovenia                                        48
Somalia                                          0
South Africa                                    45
South Korea                                     26
Spain                                          434
Sri Lanka                                       23
Sudan                                            3
Swaziland                                        1
Sweden                                         377
Switzerland                                    273
Syrian Arab Republic                             1
Taiwan                                          81
Tajikistan                                       2
Thailand                                        49
The former Yugoslav Republic of Macedonia        7
Timor-Leste                                      0
Togo                                             1
Tonga                                            0
Trinidad and Tobago                              4
Tunisia                                         50
Turkey                                         117
Turkmenistan                                     2
Uganda                                           1
Ukraine                                        406
United Arab Emirates                            28
United Kingdom                                1246
United Republic of Tanzania                      3
United States                                 3585
Uruguay                                          7
Uzbekistan                                       4
Venezuela, Bolivarian Republic of...             7
Viet Nam                                        22
Yemen                                            1
Zambia                                           1
Zimbabwe                                         0

In [142]:
df2.loc['Denmark']

EdLevel    193
Name: Denmark, dtype: int64

In [178]:
tstt = pd.DataFrame(df['Country'].value_counts()).rename(columns={'Country':'Count'})
tstt.sort_index(ascending=True)

                                           Count
Afghanistan                                   44
Albania                                       86
Algeria                                      134
Andorra                                        7
Angola                                         5
Antigua and Barbuda                            9
Argentina                                    553
Armenia                                       86
Australia                                   1903
Austria                                      839
Azerbaijan                                    49
Bahamas                                        3
Bahrain                                       18
Bangladesh                                   605
Barbados                                       3
Belarus                                      202
Belgium                                      727
Belize                                         3
Benin                                          5
Bhutan                                         2
Bolivia                                       36
Bosnia and Herzegovina                       108
Botswana                                       5
Brazil                                      1948
Brunei Darussalam                              1
Bulgaria                                     659
Burkina Faso                                   4
Burundi                                        3
Cambodia                                      30
Cameroon                                      51
Canada                                      3395
Cape Verde                                     3
Chad                                           1
Chile                                        206
China                                        664
Colombia                                     313
Congo, Republic of the...                      7
Costa Rica                                    84
Croatia                                      260
Cuba                                          30
Cyprus                                        64
Czech Republic                               764
Côte d'Ivoire                                 34
Democratic People's Republic of Korea          3
Democratic Republic of the Congo               7
Denmark                                      617
Djibouti                                       2
Dominica                                       1
Dominican Republic                            97
Ecuador                                       82
Egypt                                        323
El Salvador                                   67
Estonia                                      195
Ethiopia                                      52
Fiji                                           5
Finland                                      546
France                                      2391
Gabon                                          2
Georgia                                       80
Germany                                     5866
Ghana                                         84
Greece                                       556
Guatemala                                     67
Guinea                                         3
Guyana                                         3
Haiti                                          5
Honduras                                      27
Hong Kong (S.A.R.)                           188
Hungary                                      513
Iceland                                       49
India                                       9061
Indonesia                                    507
Iran                                         738
Iraq                                          39
Ireland                                      501
Israel                                       952
Italy                                       1576
Jamaica                                       28
Japan                                        391
Jordan                                        65
Kazakhstan                                    64
Kenya                                        249
Kuwait                                        20
Kyrgyzstan                                    19
Lao People's Democratic Republic               3
Latvia                                       136
Lebanon                                      120
Lesotho                                        3
Liberia                                        2
Libyan Arab Jamahiriya                        10
Liechtenstein                                  3
Lithuania                                    248
Luxembourg                                    61
Madagascar                                    15
Malawi                                         2
Malaysia                                     299
Maldives                                      13
Mali                                           3
Malta                                         65
Mauritania                                     7
Mauritius                                     26
Mexico                                       642
Monaco                                         4
Mongolia                                      17
Montenegro                                    17
Morocco                                      155
Mozambique                                     7
Myanmar                                       52
Namibia                                        5
Nepal                                        237
Netherlands                                 1852
New Zealand                                  524
Nicaragua                                     30
Niger                                          1
Nigeria                                      522
North Korea                                    1
Norway                                       574
Oman                                          11
Other Country (Not Listed Above)             136
Pakistan                                     923
Panama                                        33
Papua New Guinea                               1
Paraguay                                      52
Peru                                         130
Philippines                                  381
Poland                                      1922
Portugal                                     525
Qatar                                         13
Republic of Korea                             39
Republic of Moldova                           43
Romania                                      760
Russian Federation                          1694
Rwanda                                        12
Saint Kitts and Nevis                          1
Saint Vincent and the Grenadines               1
San Marino                                     2
Sao Tome and Principe                          1
Saudi Arabia                                  98
Senegal                                       21
Serbia                                       402
Seychelles                                     2
Sierra Leone                                   2
Singapore                                    303
Slovakia                                     260
Slovenia                                     298
Somalia                                       13
South Africa                                 627
South Korea                                  160
Spain                                       1604
Sri Lanka                                    372
Sudan                                         42
Swaziland                                      8
Sweden                                      1274
Switzerland                                  978
Syrian Arab Republic                          29
Taiwan                                       187
Tajikistan                                     7
Thailand                                     214
The former Yugoslav Republic of Macedonia     54
Timor-Leste                                    1
Togo                                           4
Tonga                                          1
Trinidad and Tobago                           19
Tunisia                                      130
Turkey                                       949
Turkmenistan                                   7
Uganda                                        72
Ukraine                                      868
United Arab Emirates                         158
United Kingdom                              5737
United Republic of Tanzania                   32
United States                              20949
Uruguay                                      111
Uzbekistan                                    39
Venezuela, Bolivarian Republic of...          88
Viet Nam                                     231
Yemen                                         19
Zambia                                        12
Zimbabwe                                      39

In [182]:
grp_country2.apply(lambda x: x.str.contains('Master').sum())/df['Country'].value_counts()

Afghanistan                                  0.022727
Albania                                      0.279070
Algeria                                      0.432836
Andorra                                      0.000000
Angola                                       0.200000
Antigua and Barbuda                          0.111111
Argentina                                    0.099458
Armenia                                      0.325581
Australia                                    0.143983
Austria                                      0.281287
Azerbaijan                                   0.183673
Bahamas                                      0.333333
Bahrain                                      0.111111
Bangladesh                                   0.112397
Barbados                                     0.000000
Belarus                                      0.227723
Belgium                                      0.309491
Belize                                       0.000000
Benin                                        0.200000
Bhutan                                       0.000000
Bolivia                                      0.027778
Bosnia and Herzegovina                       0.194444
Botswana                                     0.000000
Brazil                                       0.126797
Brunei Darussalam                            0.000000
Bulgaria                                     0.250379
Burkina Faso                                 0.000000
Burundi                                      0.000000
Cambodia                                     0.100000
Cameroon                                     0.196078
Canada                                       0.139912
Cape Verde                                   0.000000
Chad                                         0.000000
Chile                                        0.116505
China                                        0.194277
Colombia                                     0.115016
Congo, Republic of the...                    0.000000
Costa Rica                                   0.107143
Croatia                                      0.411538
Cuba                                         0.066667
Cyprus                                       0.343750
Czech Republic                               0.365183
Côte d'Ivoire                                0.441176
Democratic People's Republic of Korea        0.000000
Democratic Republic of the Congo             0.428571
Denmark                                      0.312804
Djibouti                                     0.500000
Dominica                                     1.000000
Dominican Republic                           0.051546
Ecuador                                      0.207317
Egypt                                        0.024768
El Salvador                                  0.104478
Estonia                                      0.241026
Ethiopia                                     0.038462
Fiji                                         0.200000
Finland                                      0.287546
France                                       0.595567
Gabon                                        0.000000
Georgia                                      0.125000
Germany                                      0.297307
Ghana                                        0.083333
Greece                                       0.327338
Guatemala                                    0.044776
Guinea                                       0.666667
Guyana                                       0.000000
Haiti                                        0.000000
Honduras                                     0.074074
Hong Kong (S.A.R.)                           0.212766
Hungary                                      0.261209
Iceland                                      0.122449
India                                        0.207152
Indonesia                                    0.065089
Iran                                         0.264228
Iraq                                         0.076923
Ireland                                      0.239521
Israel                                       0.121849
Italy                                        0.228426
Jamaica                                      0.142857
Japan                                        0.291560
Jordan                                       0.092308
Kazakhstan                                   0.171875
Kenya                                        0.040161
Kuwait                                       0.100000
Kyrgyzstan                                   0.263158
Lao People's Democratic Republic             0.333333
Latvia                                       0.242647
Lebanon                                      0.241667
Lesotho                                      0.000000
Liberia                                      0.000000
Libyan Arab Jamahiriya                       0.100000
Liechtenstein                                0.000000
Lithuania                                    0.233871
Luxembourg                                   0.393443
Madagascar                                   0.666667
Malawi                                       0.000000
Malaysia                                     0.103679
Maldives                                     0.076923
Mali                                         0.666667
Malta                                        0.184615
Mauritania                                   0.285714
Mauritius                                    0.153846
Mexico                                       0.116822
Monaco                                       0.250000
Mongolia                                     0.176471
Montenegro                                   0.235294
Morocco                                      0.270968
Mozambique                                   0.285714
Myanmar                                      0.057692
Namibia                                      0.000000
Nepal                                        0.042194
Netherlands                                  0.244060
New Zealand                                  0.127863
Nicaragua                                    0.100000
Niger                                        0.000000
Nigeria                                      0.070881
North Korea                                  0.000000
Norway                                       0.358885
Oman                                         0.363636
Other Country (Not Listed Above)             0.139706
Pakistan                                     0.146262
Panama                                       0.121212
Papua New Guinea                             0.000000
Paraguay                                     0.115385
Peru                                         0.061538
Philippines                                  0.023622
Poland                                       0.372529
Portugal                                     0.363810
Qatar                                        0.153846
Republic of Korea                            0.102564
Republic of Moldova                          0.255814
Romania                                      0.223684
Russian Federation                           0.358914
Rwanda                                       0.000000
Saint Kitts and Nevis                        0.000000
Saint Vincent and the Grenadines             0.000000
San Marino                                   0.000000
Sao Tome and Principe                        0.000000
Saudi Arabia                                 0.102041
Senegal                                      0.476190
Serbia                                       0.246269
Seychelles                                   0.000000
Sierra Leone                                 0.000000
Singapore                                    0.207921
Slovakia                                     0.403846
Slovenia                                     0.161074
Somalia                                      0.000000
South Africa                                 0.071770
South Korea                                  0.162500
Spain                                        0.270574
Sri Lanka                                    0.061828
Sudan                                        0.071429
Swaziland                                    0.125000
Sweden                                       0.295918
Switzerland                                  0.279141
Syrian Arab Republic                         0.034483
Taiwan                                       0.433155
Tajikistan                                   0.285714
Thailand                                     0.228972
The former Yugoslav Republic of Macedonia    0.129630
Timor-Leste                                  0.000000
Togo                                         0.250000
Tonga                                        0.000000
Trinidad and Tobago                          0.210526
Tunisia                                      0.384615
Turkey                                       0.123288
Turkmenistan                                 0.285714
Uganda                                       0.013889
Ukraine                                      0.467742
United Arab Emirates                         0.177215
United Kingdom                               0.217187
United Republic of Tanzania                  0.093750
United States                                0.171130
Uruguay                                      0.063063
Uzbekistan                                   0.102564
Venezuela, Bolivarian Republic of...         0.079545
Viet Nam                                     0.095238
Yemen                                        0.052632
Zambia                                       0.083333
Zimbabwe                                     0.000000
dtype: float64

In [186]:
grp_ctry_master = grp_country2.apply(lambda x: x.str.contains('Master').sum())
grp_ctry_all = df['Country'].value_counts()
grp_concat = pd.concat([grp_ctry_master,grp_ctry_all], axis='columns', sort=False)

grp_concat.rename(columns={'EdLevel':'Masters','Country':'All'}, inplace=True)

In [204]:
grp_concat['PctMaster'] = (grp_concat['Masters']/grp_concat['All'])

In [205]:
grp_concat

                                           Masters    All  PctMaster
Afghanistan                                      1     44   0.022727
Albania                                         24     86   0.279070
Algeria                                         58    134   0.432836
Andorra                                          0      7   0.000000
Angola                                           1      5   0.200000
Antigua and Barbuda                              1      9   0.111111
Argentina                                       55    553   0.099458
Armenia                                         28     86   0.325581
Australia                                      274   1903   0.143983
Austria                                        236    839   0.281287
Azerbaijan                                       9     49   0.183673
Bahamas                                          1      3   0.333333
Bahrain                                          2     18   0.111111
Bangladesh                                      68    605   0.112397
Barbados                                         0      3   0.000000
Belarus                                         46    202   0.227723
Belgium                                        225    727   0.309491
Belize                                           0      3   0.000000
Benin                                            1      5   0.200000
Bhutan                                           0      2   0.000000
Bolivia                                          1     36   0.027778
Bosnia and Herzegovina                          21    108   0.194444
Botswana                                         0      5   0.000000
Brazil                                         247   1948   0.126797
Brunei Darussalam                                0      1   0.000000
Bulgaria                                       165    659   0.250379
Burkina Faso                                     0      4   0.000000
Burundi                                          0      3   0.000000
Cambodia                                         3     30   0.100000
Cameroon                                        10     51   0.196078
Canada                                         475   3395   0.139912
Cape Verde                                       0      3   0.000000
Chad                                             0      1   0.000000
Chile                                           24    206   0.116505
China                                          129    664   0.194277
Colombia                                        36    313   0.115016
Congo, Republic of the...                        0      7   0.000000
Costa Rica                                       9     84   0.107143
Croatia                                        107    260   0.411538
Cuba                                             2     30   0.066667
Cyprus                                          22     64   0.343750
Czech Republic                                 279    764   0.365183
Côte d'Ivoire                                   15     34   0.441176
Democratic People's Republic of Korea            0      3   0.000000
Democratic Republic of the Congo                 3      7   0.428571
Denmark                                        193    617   0.312804
Djibouti                                         1      2   0.500000
Dominica                                         1      1   1.000000
Dominican Republic                               5     97   0.051546
Ecuador                                         17     82   0.207317
Egypt                                            8    323   0.024768
El Salvador                                      7     67   0.104478
Estonia                                         47    195   0.241026
Ethiopia                                         2     52   0.038462
Fiji                                             1      5   0.200000
Finland                                        157    546   0.287546
France                                        1424   2391   0.595567
Gabon                                            0      2   0.000000
Georgia                                         10     80   0.125000
Germany                                       1744   5866   0.297307
Ghana                                            7     84   0.083333
Greece                                         182    556   0.327338
Guatemala                                        3     67   0.044776
Guinea                                           2      3   0.666667
Guyana                                           0      3   0.000000
Haiti                                            0      5   0.000000
Honduras                                         2     27   0.074074
Hong Kong (S.A.R.)                              40    188   0.212766
Hungary                                        134    513   0.261209
Iceland                                          6     49   0.122449
India                                         1877   9061   0.207152
Indonesia                                       33    507   0.065089
Iran                                           195    738   0.264228
Iraq                                             3     39   0.076923
Ireland                                        120    501   0.239521
Israel                                         116    952   0.121849
Italy                                          360   1576   0.228426
Jamaica                                          4     28   0.142857
Japan                                          114    391   0.291560
Jordan                                           6     65   0.092308
Kazakhstan                                      11     64   0.171875
Kenya                                           10    249   0.040161
Kuwait                                           2     20   0.100000
Kyrgyzstan                                       5     19   0.263158
Lao People's Democratic Republic                 1      3   0.333333
Latvia                                          33    136   0.242647
Lebanon                                         29    120   0.241667
Lesotho                                          0      3   0.000000
Liberia                                          0      2   0.000000
Libyan Arab Jamahiriya                           1     10   0.100000
Liechtenstein                                    0      3   0.000000
Lithuania                                       58    248   0.233871
Luxembourg                                      24     61   0.393443
Madagascar                                      10     15   0.666667
Malawi                                           0      2   0.000000
Malaysia                                        31    299   0.103679
Maldives                                         1     13   0.076923
Mali                                             2      3   0.666667
Malta                                           12     65   0.184615
Mauritania                                       2      7   0.285714
Mauritius                                        4     26   0.153846
Mexico                                          75    642   0.116822
Monaco                                           1      4   0.250000
Mongolia                                         3     17   0.176471
Montenegro                                       4     17   0.235294
Morocco                                         42    155   0.270968
Mozambique                                       2      7   0.285714
Myanmar                                          3     52   0.057692
Namibia                                          0      5   0.000000
Nepal                                           10    237   0.042194
Netherlands                                    452   1852   0.244060
New Zealand                                     67    524   0.127863
Nicaragua                                        3     30   0.100000
Niger                                            0      1   0.000000
Nigeria                                         37    522   0.070881
North Korea                                      0      1   0.000000
Norway                                         206    574   0.358885
Oman                                             4     11   0.363636
Other Country (Not Listed Above)                19    136   0.139706
Pakistan                                       135    923   0.146262
Panama                                           4     33   0.121212
Papua New Guinea                                 0      1   0.000000
Paraguay                                         6     52   0.115385
Peru                                             8    130   0.061538
Philippines                                      9    381   0.023622
Poland                                         716   1922   0.372529
Portugal                                       191    525   0.363810
Qatar                                            2     13   0.153846
Republic of Korea                                4     39   0.102564
Republic of Moldova                             11     43   0.255814
Romania                                        170    760   0.223684
Russian Federation                             608   1694   0.358914
Rwanda                                           0     12   0.000000
Saint Kitts and Nevis                            0      1   0.000000
Saint Vincent and the Grenadines                 0      1   0.000000
San Marino                                       0      2   0.000000
Sao Tome and Principe                            0      1   0.000000
Saudi Arabia                                    10     98   0.102041
Senegal                                         10     21   0.476190
Serbia                                          99    402   0.246269
Seychelles                                       0      2   0.000000
Sierra Leone                                     0      2   0.000000
Singapore                                       63    303   0.207921
Slovakia                                       105    260   0.403846
Slovenia                                        48    298   0.161074
Somalia                                          0     13   0.000000
South Africa                                    45    627   0.071770
South Korea                                     26    160   0.162500
Spain                                          434   1604   0.270574
Sri Lanka                                       23    372   0.061828
Sudan                                            3     42   0.071429
Swaziland                                        1      8   0.125000
Sweden                                         377   1274   0.295918
Switzerland                                    273    978   0.279141
Syrian Arab Republic                             1     29   0.034483
Taiwan                                          81    187   0.433155
Tajikistan                                       2      7   0.285714
Thailand                                        49    214   0.228972
The former Yugoslav Republic of Macedonia        7     54   0.129630
Timor-Leste                                      0      1   0.000000
Togo                                             1      4   0.250000
Tonga                                            0      1   0.000000
Trinidad and Tobago                              4     19   0.210526
Tunisia                                         50    130   0.384615
Turkey                                         117    949   0.123288
Turkmenistan                                     2      7   0.285714
Uganda                                           1     72   0.013889
Ukraine                                        406    868   0.467742
United Arab Emirates                            28    158   0.177215
United Kingdom                                1246   5737   0.217187
United Republic of Tanzania                      3     32   0.093750
United States                                 3585  20949   0.171130
Uruguay                                          7    111   0.063063
Uzbekistan                                       4     39   0.102564
Venezuela, Bolivarian Republic of...             7     88   0.079545
Viet Nam                                        22    231   0.095238
Yemen                                            1     19   0.052632
Zambia                                           1     12   0.083333
Zimbabwe                                         0     39   0.000000

In [194]:
grp_country2.apply(lambda x: x.str.contains('Master').count())

Country
Afghanistan                                     39
Albania                                         81
Algeria                                        122
Andorra                                          7
Angola                                           3
Antigua and Barbuda                              7
Argentina                                      533
Armenia                                         82
Australia                                     1852
Austria                                        799
Azerbaijan                                      47
Bahamas                                          3
Bahrain                                         17
Bangladesh                                     574
Barbados                                         2
Belarus                                        199
Belgium                                        717
Belize                                           3
Benin                                            4
Bhutan                                           2
Bolivia                                         36
Bosnia and Herzegovina                         107
Botswana                                         5
Brazil                                        1924
Brunei Darussalam                                1
Bulgaria                                       644
Burkina Faso                                     3
Burundi                                          3
Cambodia                                        29
Cameroon                                        48
Canada                                        3269
Cape Verde                                       2
Chad                                             1
Chile                                          204
China                                          645
Colombia                                       304
Congo, Republic of the...                        7
Costa Rica                                      83
Croatia                                        258
Cuba                                            28
Cyprus                                          62
Czech Republic                                 750
Côte d'Ivoire                                   34
Democratic People's Republic of Korea            3
Democratic Republic of the Congo                 7
Denmark                                        599
Djibouti                                         2
Dominica                                         1
Dominican Republic                              96
Ecuador                                         82
Egypt                                          318
El Salvador                                     65
Estonia                                        191
Ethiopia                                        50
Fiji                                             5
Finland                                        531
France                                        2324
Gabon                                            2
Georgia                                         78
Germany                                       5674
Ghana                                           83
Greece                                         547
Guatemala                                       66
Guinea                                           3
Guyana                                           3
Haiti                                            5
Honduras                                        25
Hong Kong (S.A.R.)                             184
Hungary                                        504
Iceland                                         46
India                                         8699
Indonesia                                      486
Iran                                           718
Iraq                                            36
Ireland                                        492
Israel                                         927
Italy                                         1542
Jamaica                                         28
Japan                                          382
Jordan                                          61
Kazakhstan                                      64
Kenya                                          240
Kuwait                                          19
Kyrgyzstan                                      19
Lao People's Democratic Republic                 3
Latvia                                         133
Lebanon                                        117
Lesotho                                          3
Liberia                                          2
Libyan Arab Jamahiriya                          10
Liechtenstein                                    3
Lithuania                                      245
Luxembourg                                      61
Madagascar                                      15
Malawi                                           2
Malaysia                                       286
Maldives                                        13
Mali                                             3
Malta                                           64
Mauritania                                       7
Mauritius                                       24
Mexico                                         632
Monaco                                           4
Mongolia                                        16
Montenegro                                      17
Morocco                                        148
Mozambique                                       6
Myanmar                                         49
Namibia                                          4
Nepal                                          233
Netherlands                                   1808
New Zealand                                    513
Nicaragua                                       30
Niger                                            1
Nigeria                                        490
North Korea                                      1
Norway                                         567
Oman                                            11
Other Country (Not Listed Above)               124
Pakistan                                       891
Panama                                          33
Papua New Guinea                                 1
Paraguay                                        52
Peru                                           126
Philippines                                    364
Poland                                        1889
Portugal                                       514
Qatar                                           12
Republic of Korea                               37
Republic of Moldova                             42
Romania                                        750
Russian Federation                            1648
Rwanda                                          12
Saint Kitts and Nevis                            1
Saint Vincent and the Grenadines                 1
San Marino                                       2
Sao Tome and Principe                            1
Saudi Arabia                                    92
Senegal                                         20
Serbia                                         392
Seychelles                                       2
Sierra Leone                                     1
Singapore                                      293
Slovakia                                       253
Slovenia                                       294
Somalia                                         13
South Africa                                   580
South Korea                                    155
Spain                                         1563
Sri Lanka                                      356
Sudan                                           40
Swaziland                                        7
Sweden                                        1246
Switzerland                                    921
Syrian Arab Republic                            27
Taiwan                                         184
Tajikistan                                       7
Thailand                                       209
The former Yugoslav Republic of Macedonia       54
Timor-Leste                                      1
Togo                                             3
Tonga                                            0
Trinidad and Tobago                             19
Tunisia                                        122
Turkey                                         928
Turkmenistan                                     6
Uganda                                          69
Ukraine                                        853
United Arab Emirates                           151
United Kingdom                                5599
United Republic of Tanzania                     32
United States                                20605
Uruguay                                        110
Uzbekistan                                      37
Venezuela, Bolivarian Republic of...            85
Viet Nam                                       224
Yemen                                           19
Zambia                                          12
Zimbabwe                                        38
Name: EdLevel, dtype: int64

In [203]:
df[(df['Country']=='Afghanistan') & (df['EdLevel'].str.contains('Master'))]

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
32971,33178,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than prop...","Not employed, and not looking for work",Afghanistan,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Completed an industry certification program (e...,NaN,NaN,20,10,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;C#;HTML/CSS;Java;J...,Bash/Shell/PowerShell;C;C++;C#;HTML/CSS;Java;J...,Microsoft SQL Server;MySQL;SQLite,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Android;iOS;Linux;MacOS;Microsoft Azure;Windows,Android;iOS;Linux;MacOS;Microsoft Azure;Windows,ASP.NET;jQuery,ASP.NET;jQuery,.NET;.NET Core;Node.js;Xamarin,.NET;.NET Core;Node.js;Xamarin,Android Studio;Visual Studio;Visual Studio Cod...,MacOS,I do not use containers,NaN,Useful for immutable record keeping outside of...,Yes,Yes,Yes,I don't use social media,In real life (in person),Username,2010,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,11-30 minutes,Not sure / can't remember,NaN,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Industry news about technologies you're intere...,NaN,Man,No,NaN,NaN,NaN,Too long,Neither easy nor difficult

In [206]:
grp_country2.apply(lambda x: x.str.contains('Master').mean())

Country
Afghanistan                                  0.025641
Albania                                      0.296296
Algeria                                      0.475410
Andorra                                      0.000000
Angola                                       0.333333
Antigua and Barbuda                          0.142857
Argentina                                    0.103189
Armenia                                      0.341463
Australia                                    0.147948
Austria                                      0.295369
Azerbaijan                                   0.191489
Bahamas                                      0.333333
Bahrain                                      0.117647
Bangladesh                                   0.118467
Barbados                                     0.000000
Belarus                                      0.231156
Belgium                                      0.313808
Belize                                       0.000000
Benin                                        0.250000
Bhutan                                       0.000000
Bolivia                                      0.027778
Bosnia and Herzegovina                       0.196262
Botswana                                     0.000000
Brazil                                       0.128378
Brunei Darussalam                            0.000000
Bulgaria                                     0.256211
Burkina Faso                                 0.000000
Burundi                                      0.000000
Cambodia                                     0.103448
Cameroon                                     0.208333
Canada                                       0.145304
Cape Verde                                   0.000000
Chad                                         0.000000
Chile                                        0.117647
China                                        0.200000
Colombia                                     0.118421
Congo, Republic of the...                    0.000000
Costa Rica                                   0.108434
Croatia                                      0.414729
Cuba                                         0.071429
Cyprus                                       0.354839
Czech Republic                               0.372000
Côte d'Ivoire                                0.441176
Democratic People's Republic of Korea        0.000000
Democratic Republic of the Congo             0.428571
Denmark                                      0.322204
Djibouti                                     0.500000
Dominica                                     1.000000
Dominican Republic                           0.052083
Ecuador                                      0.207317
Egypt                                        0.025157
El Salvador                                  0.107692
Estonia                                      0.246073
Ethiopia                                     0.040000
Fiji                                         0.200000
Finland                                      0.295669
France                                       0.612737
Gabon                                        0.000000
Georgia                                      0.128205
Germany                                      0.307367
Ghana                                        0.084337
Greece                                       0.332724
Guatemala                                    0.045455
Guinea                                       0.666667
Guyana                                       0.000000
Haiti                                        0.000000
Honduras                                     0.080000
Hong Kong (S.A.R.)                           0.217391
Hungary                                      0.265873
Iceland                                      0.130435
India                                        0.215772
Indonesia                                    0.067901
Iran                                         0.271588
Iraq                                         0.083333
Ireland                                      0.243902
Israel                                       0.125135
Italy                                        0.233463
Jamaica                                      0.142857
Japan                                        0.298429
Jordan                                       0.098361
Kazakhstan                                   0.171875
Kenya                                        0.041667
Kuwait                                       0.105263
Kyrgyzstan                                   0.263158
Lao People's Democratic Republic             0.333333
Latvia                                       0.248120
Lebanon                                      0.247863
Lesotho                                      0.000000
Liberia                                      0.000000
Libyan Arab Jamahiriya                       0.100000
Liechtenstein                                0.000000
Lithuania                                    0.236735
Luxembourg                                   0.393443
Madagascar                                   0.666667
Malawi                                       0.000000
Malaysia                                     0.108392
Maldives                                     0.076923
Mali                                         0.666667
Malta                                        0.187500
Mauritania                                   0.285714
Mauritius                                    0.166667
Mexico                                       0.118671
Monaco                                       0.250000
Mongolia                                     0.187500
Montenegro                                   0.235294
Morocco                                      0.283784
Mozambique                                   0.333333
Myanmar                                      0.061224
Namibia                                      0.000000
Nepal                                        0.042918
Netherlands                                  0.250000
New Zealand                                  0.130604
Nicaragua                                    0.100000
Niger                                        0.000000
Nigeria                                      0.075510
North Korea                                  0.000000
Norway                                       0.363316
Oman                                         0.363636
Other Country (Not Listed Above)             0.153226
Pakistan                                     0.151515
Panama                                       0.121212
Papua New Guinea                             0.000000
Paraguay                                     0.115385
Peru                                         0.063492
Philippines                                  0.024725
Poland                                       0.379037
Portugal                                     0.371595
Qatar                                        0.166667
Republic of Korea                            0.108108
Republic of Moldova                          0.261905
Romania                                      0.226667
Russian Federation                           0.368932
Rwanda                                       0.000000
Saint Kitts and Nevis                        0.000000
Saint Vincent and the Grenadines             0.000000
San Marino                                   0.000000
Sao Tome and Principe                        0.000000
Saudi Arabia                                 0.108696
Senegal                                      0.500000
Serbia                                       0.252551
Seychelles                                   0.000000
Sierra Leone                                 0.000000
Singapore                                    0.215017
Slovakia                                     0.415020
Slovenia                                     0.163265
Somalia                                      0.000000
South Africa                                 0.077586
South Korea                                  0.167742
Spain                                        0.277671
Sri Lanka                                    0.064607
Sudan                                        0.075000
Swaziland                                    0.142857
Sweden                                       0.302568
Switzerland                                  0.296417
Syrian Arab Republic                         0.037037
Taiwan                                       0.440217
Tajikistan                                   0.285714
Thailand                                     0.234450
The former Yugoslav Republic of Macedonia    0.129630
Timor-Leste                                  0.000000
Togo                                         0.333333
Tonga                                             NaN
Trinidad and Tobago                          0.210526
Tunisia                                      0.409836
Turkey                                       0.126078
Turkmenistan                                 0.333333
Uganda                                       0.014493
Ukraine                                      0.475967
United Arab Emirates                         0.185430
United Kingdom                               0.222540
United Republic of Tanzania                  0.093750
United States                                0.173987
Uruguay                                      0.063636
Uzbekistan                                   0.108108
Venezuela, Bolivarian Republic of...         0.082353
Viet Nam                                     0.098214
Yemen                                        0.052632
Zambia                                       0.083333
Zimbabwe                                     0.000000
Name: EdLevel, dtype: float64