## (Part 1)
https://www.youtube.com/watch?v=ZyhVh-qRZPA

In [45]:
import pandas as pd

In [49]:
import os

In [61]:
os.chdir('C:\\Users\\Joshua\Desktop\\PERSONAL\\Joshua Harvey\\education\\youtube\\Corey Schafer\\Python Tutorials\\data')

C:/data\survey_results_public.csv

In [62]:
df = pd.read_csv('survey_results_public.csv')
df_schema = pd.read_csv('survey_results_schema.csv')

In [63]:
df.shape

(88883, 85)

In [26]:
df.head(3)

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"I’m not actively looking, but I am open to new...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult

In [56]:
pd.set_option('display.max_columns', 85)

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88883 entries, 0 to 88882
Data columns (total 85 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Respondent              88883 non-null  int64
 1   MainBranch              88331 non-null  object
 2   Hobbyist                88883 non-null  object
 3   OpenSourcer             88883 non-null  object
 4   OpenSource              86842 non-null  object
 5   Employment              87181 non-null  object
 6   Country                 88751 non-null  object
 7   Student                 87014 non-null  object
 8   EdLevel                 86390 non-null  object
 9   UndergradMajor          75614 non-null  object
 10  EduOther                84260 non-null  object
 11  OrgSize                 71791 non-null  object
 12  DevType                 81335 non-null  object
 13  YearsCode               87938 non-null  object
 14  Age1stCode              87634 non-null  object
 15  YearsCodePro            74331 non-null  object
 16  CareerSat               72847 non-null  object
 17  JobSat                  70988 non-null  object
 18  MgrIdiot                61159 non-null  object
 19  MgrMoney                61157 non-null  object
 20  MgrWant                 61232 non-null  object
 21  JobSeek                 80555 non-null  object
 22  LastHireDate            79854 non-null  object
 23  LastInt                 67155 non-null  object
 24  FizzBuzz                71344 non-null  object
 25  JobFactors              79371 non-null  object
 26  ResumeUpdate            77877 non-null  object
 27  CurrencySymbol          71392 non-null  object
 28  CurrencyDesc            71392 non-null  object
 29  CompTotal               55945 non-null  float64
 30  CompFreq                63268 non-null  object
 31  ConvertedComp           55823 non-null  float64
 32  WorkWeekHrs             64503 non-null  float64
 33  WorkPlan                68914 non-null  object
 34  WorkChallenge           68141 non-null  object
 35  WorkRemote              70284 non-null  object
 36  WorkLoc                 70055 non-null  object
 37  ImpSyn                  71779 non-null  object
 38  CodeRev                 70390 non-null  object
 39  CodeRevHrs              49790 non-null  float64
 40  UnitTests               62668 non-null  object
 41  PurchaseHow             61108 non-null  object
 42  PurchaseWhat            62029 non-null  object
 43  LanguageWorkedWith      87569 non-null  object
 44  LanguageDesireNextYear  84088 non-null  object
 45  DatabaseWorkedWith      76026 non-null  object
 46  DatabaseDesireNextYear  69147 non-null  object
 47  PlatformWorkedWith      80714 non-null  object
 48  PlatformDesireNextYear  77443 non-null  object
 49  WebFrameWorkedWith      65022 non-null  object
 50  WebFrameDesireNextYear  62944 non-null  object
 51  MiscTechWorkedWith      59586 non-null  object
 52  MiscTechDesireNextYear  64511 non-null  object
 53  DevEnviron              87317 non-null  object
 54  OpSys                   87851 non-null  object
 55  Containers              85366 non-null  object
 56  BlockchainOrg           48175 non-null  object
 57  BlockchainIs            60165 non-null  object
 58  BetterLife              86269 non-null  object
 59  ITperson                87141 non-null  object
 60  OffOn                   86663 non-null  object
 61  SocialMedia             84437 non-null  object
 62  Extraversion            87305 non-null  object
 63  ScreenName              80486 non-null  object
 64  SOVisit1st              83877 non-null  object
 65  SOVisitFreq             88263 non-null  object
 66  SOVisitTo               88086 non-null  object
 67  SOFindAnswer            87816 non-null  object
 68  SOTimeSaved             86344 non-null  object
 69  SOHowMuchTime           68378 non-null  object
 70  SOAccount               87828 non-null  object
 71  SOPartFreq              74692 non-null  object
 72  SOJobs                  88066 non-null  object
 73  EntTeams                87841 non-null  object
 74  SOComm                  88131 non-null  object
 75  WelcomeChange           85855 non-null  object
 76  SONewContent            69560 non-null  object
 77  Age                     79210 non-null  float64
 78  Gender                  85406 non-null  object
 79  Trans                   83607 non-null  object
 80  Sexuality               76147 non-null  object
 81  Ethnicity               76668 non-null  object
 82  Dependents              83059 non-null  object
 83  SurveyLength            86984 non-null  object
 84  SurveyEase              87081 non-null  object
dtypes: float64(5), int64(1), object(79)
memory usage: 57.6+ MB

In [58]:
df.tail()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;JavaScript;Other(s):,C++;HTML/CSS;JavaScript;SQL;WebAssembly;Other(s):,Firebase;SQLite,Firebase;MySQL;SQLite,Linux,Google Cloud Platform;Linux,jQuery,jQuery;Vue.js,Node.js,React Native;Unity 3D;Unreal Engine,Atom;Visual Studio;Visual Studio Code,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,What?,YouTube,NaN,Username,I don't remember,A few times per week,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not at all",NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,NaN,NaN,8,11,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,C;C++;C#;HTML/CSS;Java;Objective-C;SQL;Swift,DynamoDB;MariaDB;Microsoft SQL Server;MySQL,MariaDB;MySQL;Oracle;SQLite,iOS;Linux;MacOS;WordPress,Android;AWS;Google Cloud Platform;IBM Cloud or...,Django;jQuery;React.js,Django,Unity 3D;Unreal Engine,NaN,Android Studio;Atom;Eclipse;NetBeans;Notepad++...,Linux-based,Production,NaN,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Also Yes,Yes,WhatsApp,In real life (in person),NaN,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

## (Part 2)
https://www.youtube.com/watch?v=zmdjNSmRXF4

In [105]:
# -- iloc uses integers for rows/columns respectively 
df.iloc[0]

Respondent                                                      1
MainBranch                 I am a student who is learning to code
Hobbyist                                                      Yes
OpenSourcer                                                 Never
OpenSource      The quality of OSS and closed source software ...
                                      ...
Sexuality                                 Straight / Heterosexual
Ethnicity                                                     NaN
Dependents                                                     No
SurveyLength                                Appropriate in length
SurveyEase                             Neither easy nor difficult
Name: 0, Length: 85, dtype: object

In [59]:
df.loc[[1,2,3],['Respondent','Hobbyist','Student','Sexuality']]

   Respondent Hobbyist         Student                Sexuality
1           2       No  Yes, full-time  Straight / Heterosexual
2           3      Yes              No  Straight / Heterosexual
3           4       No              No  Straight / Heterosexual

In [60]:
unique_sexuality = set(df['Sexuality'])

In [61]:
unique_sexuality

{'Bisexual',
 'Bisexual;Gay or Lesbian',
 'Bisexual;Gay or Lesbian;Straight / Heterosexual',
 'Bisexual;Straight / Heterosexual',
 'Gay or Lesbian',
 'Gay or Lesbian;Straight / Heterosexual',
 'Straight / Heterosexual',
 nan}

In [62]:
df['Sexuality'].value_counts()

Straight / Heterosexual                            70155
Bisexual                                            3440
Gay or Lesbian                                      1798
Bisexual;Straight / Heterosexual                     494
Bisexual;Gay or Lesbian                              114
Bisexual;Gay or Lesbian;Straight / Heterosexual      108
Gay or Lesbian;Straight / Heterosexual                38
Name: Sexuality, dtype: int64

In [63]:
# -- makes more sense to display as a vertical list than a data-frame row
# -- unable to determine how to display all columns - attempted with pd.set_option  
df.iloc[0]

Respondent                                                      1
MainBranch                 I am a student who is learning to code
Hobbyist                                                      Yes
OpenSourcer                                                 Never
OpenSource      The quality of OSS and closed source software ...
                                      ...
Sexuality                                 Straight / Heterosexual
Ethnicity                                                     NaN
Dependents                                                     No
SurveyLength                                Appropriate in length
SurveyEase                             Neither easy nor difficult
Name: 0, Length: 85, dtype: object

In [64]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

In [66]:
# -- ranges can also be used with column header fields with .loc only
df.loc[0:2,'Respondent':'Employment']

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work"
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work"
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time

## (Part 3)
https://www.youtube.com/watch?v=W9XjRYFkkyw

In [68]:
people = {
    "initials": ["JDH", "JKM", "RLW", "DEM"],
    "first_name":["Joshua","John","Rebecca", "Diane"],
    "last_name":["Harvey", "Marsh", "Winter", "McCabe"],
    "age": [31,58,27,60]
}

In [69]:
peeps = pd.DataFrame(people)

In [70]:
peeps[['first_name']]

  first_name
0     Joshua
1       John
2    Rebecca
3      Diane

In [71]:
peeps.set_index('initials')

         first_name last_name  age
initials
JDH          Joshua    Harvey   31
JKM            John     Marsh   58
RLW         Rebecca    Winter   27
DEM           Diane    McCabe   60

In [72]:
# -- pandas doesn't actually modify data in place unless specified

peeps

  initials first_name last_name  age
0      JDH     Joshua    Harvey   31
1      JKM       John     Marsh   58
2      RLW    Rebecca    Winter   27
3      DEM      Diane    McCabe   60

In [73]:
peeps.set_index('initials', inplace=True)

In [74]:
peeps

         first_name last_name  age
initials
JDH          Joshua    Harvey   31
JKM            John     Marsh   58
RLW         Rebecca    Winter   27
DEM           Diane    McCabe   60

In [99]:
peeps.index

Index(['JDH', 'JKM', 'RLW', 'DEM'], dtype='object', name='initials')

In [100]:
peeps.loc['JDH']

first_name    Joshua
last_name     Harvey
age               31
Name: JDH, dtype: object

In [113]:
# -- must be careful not to use range of integers inside nested brackets

peeps.iloc[0,0:2]

first_name    Joshua
last_name     Harvey
Name: JDH, dtype: object

In [114]:
peeps.reset_index(inplace=True)

In [115]:
peeps

  initials first_name last_name  age
0      JDH     Joshua    Harvey   31
1      JKM       John     Marsh   58
2      RLW    Rebecca    Winter   27
3      DEM      Diane    McCabe   60

In [120]:
df.set_index('Respondent', inplace=True)

In [121]:
df.iloc[:,0:3]

,MainBranch,Hobbyist,OpenSourcer
Respondent,,,
1,I am a student who is learning to code,Yes,Never
2,I am a student who is learning to code,No,Less than once per year
3,"I am not primarily a developer, but I write co...",Yes,Never
4,I am a developer by profession,No,Never
5,I am a developer by profession,Yes,Once a month or more often
...,...,...,...
88377,NaN,Yes,Less than once a month but more than once per ...
88601,NaN,No,Never
88802,NaN,No,Never
88816,NaN,No,Never
88863,NaN,Yes,Less than once per year

In [124]:
df.reset_index(inplace=True)

In [64]:
# -- importing data and setting the index during import 

fd = pd.read_csv('./survey_results_public.csv', index_col='Respondent')

In [129]:
fd.loc[:,'Hobbyist':'Employment']

,Hobbyist,OpenSourcer,OpenSource,Employment
Respondent,,,,
1,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work"
2,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work"
3,Yes,Never,The quality of OSS and closed source software ...,Employed full-time
4,No,Never,The quality of OSS and closed source software ...,Employed full-time
5,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time
...,...,...,...,...
88377,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work"
88601,No,Never,The quality of OSS and closed source software ...,NaN
88802,No,Never,NaN,Employed full-time
88816,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em..."
88863,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work"

In [131]:
df_schema.set_index('Column', inplace=True)

In [65]:
df_schema

          Column                                       QuestionText
0     Respondent  Randomized respondent ID number (not in order ...
1     MainBranch  Which of the following options best describes ...
2       Hobbyist                            Do you code as a hobby?
3    OpenSourcer        How often do you contribute to open source?
4     OpenSource  How do you feel about the quality of open sour...
..           ...                                                ...
80     Sexuality  Which of the following do you currently identi...
81     Ethnicity  Which of the following do you identify as? Ple...
82    Dependents  Do you have any dependents (e.g., children, el...
83  SurveyLength  How do you feel about the length of the survey...
84    SurveyEase  How easy or difficult was this survey to compl...

[85 rows x 2 columns]

In [133]:
df_schema.loc['MgrIdiot', 'QuestionText']

'How confident are you that your manager knows what they’re doing?'

In [171]:
pd.set_option('display.max_rows',100)

In [140]:
df_schema.sort_index(ascending=False)

                                                             QuestionText
Column
YearsCodePro            How many years have you coded professionally (...
YearsCode               Including any education, how many years have y...
WorkWeekHrs              On average, how many hours per week do you work?
WorkRemote                                How often do you work remotely?
WorkPlan                          How structured or planned is your work?
WorkLoc                                   Where would you prefer to work?
WorkChallenge           Of these options, what are your greatest chall...
WelcomeChange           Compared to last year, how welcome do you feel...
WebFrameWorkedWith      Which of the following web frameworks have you...
WebFrameDesireNextYear  Which of the following web frameworks have you...
UnitTests               Does your company regularly employ unit tests ...
UndergradMajor          What was your main or most important field of ...
Trans                                     Do you identify as transgender?
SurveyLength            How do you feel about the length of the survey...
SurveyEase              How easy or difficult was this survey to compl...
Student                 Are you currently enrolled in a formal, degree...
SocialMedia                   What social media site do you use the most?
Sexuality               Which of the following do you currently identi...
ScreenName                                           What do you call it?
SOVisitTo               I visit Stack Overflow to... (check all that a...
SOVisitFreq             How frequently would you say you visit Stack O...
SOVisit1st              To the best of your memory, when did you first...
SOTimeSaved             Think back to the last time you solved a codin...
SOPartFreq              How frequently would you say you participate i...
SONewContent            Would you like to see any of the following on ...
SOJobs                  Have you ever used or visited Stack Overflow J...
SOHowMuchTime           About how much time did you save? If you're no...
SOFindAnswer            On average, how many times a week do you find ...
SOComm                  Do you consider yourself a member of the Stack...
SOAccount                           Do you have a Stack Overflow account?
ResumeUpdate            Think back to the last time you updated your r...
Respondent              Randomized respondent ID number (not in order ...
PurchaseWhat            What level of influence do you, personally, ha...
PurchaseHow             How does your company make decisions about pur...
PlatformWorkedWith      Which of the following platforms have you done...
PlatformDesireNextYear  Which of the following platforms have you done...
OrgSize                 Approximately how many people are employed by ...
OpenSourcer                   How often do you contribute to open source?
OpenSource              How do you feel about the quality of open sour...
OpSys                   What is the primary operating system in which ...
OffOn                         Have you tried turning it off and on again?
MiscTechWorkedWith      Which of the following other frameworks, libra...
MiscTechDesireNextYear  Which of the following other frameworks, libra...
MgrWant                 Do you want to become a manager yourself in th...
MgrMoney                Do you believe that you need to be a manager t...
MgrIdiot                How confident are you that your manager knows ...
MainBranch              Which of the following options best describes ...
LastInt                 In your most recent successful job interview (...
LastHireDate            When was the last time that you took a job wit...
LanguageWorkedWith      Which of the following programming, scripting,...
LanguageDesireNextYear  Which of the following programming, scripting,...
JobSeek                 Which of the following best describes your cur...
JobSat                  How satisfied are you with your current job? (...
JobFactors              Imagine that you are deciding between two job ...
ImpSyn                  For the specific work you do, and the years of...
ITperson                 Are you the "IT support person" for your family?
Hobbyist                                          Do you code as a hobby?
Gender                  Which of the following do you currently identi...
FizzBuzz                Have you ever been asked to solve FizzBuzz in ...
Extraversion              Do you prefer online chat or IRL conversations?
Ethnicity               Which of the following do you identify as? Ple...
EntTeams                Have you ever used Stack Overflow for Enterpri...
Employment              Which of the following best describes your cur...
EduOther                Which of the following types of non-degree edu...
EdLevel                 Which of the following best describes the high...
DevType                 Which of the following describe you? Please se...
DevEnviron              Which development environment(s) do you use re...
Dependents              Do you have any dependents (e.g., children, el...
DatabaseWorkedWith      Which of the following database environments h...
DatabaseDesireNextYear  Which of the following database environments h...
CurrencySymbol          Which currency do you use day-to-day? If your ...
CurrencyDesc            Which currency do you use day-to-day? If your ...
Country                         In which country do you currently reside?
ConvertedComp           Salary converted to annual USD salaries using ...
Containers              How do you use containers (Docker, Open Contai...
CompTotal               What is your current total compensation (salar...
CompFreq                 Is that compensation weekly, monthly, or yearly?
CodeRevHrs              On average, how many hours per week do you spe...
CodeRev                          Do you review code as part of your work?
CareerSat               Overall, how satisfied are you with your caree...
BlockchainOrg           How is your organization thinking about or imp...
BlockchainIs            Blockchain / cryptocurrency technology is prim...
BetterLife              Do you think people born today will have a bet...
Age1stCode              At what age did you write your first line of c...
Age                     What is your age (in years)? If you prefer not...

## (Part 4)
https://www.youtube.com/watch?v=Lw2rlcxScZY

In [75]:
peeps

         first_name last_name  age
initials
JDH          Joshua    Harvey   31
JKM            John     Marsh   58
RLW         Rebecca    Winter   27
DEM           Diane    McCabe   60

In [76]:
# -- filter mask
# -- filter mask can be dataframe but not if it's going to be applied back to selection
# -- notice the () parenthesis when setting the variable
# -- filter is a built-in keyword so use an abbreviation 

filt_age = (peeps['age'] > 35)
filt_name = (peeps['last_name'] == 'Winter')

filt_all = (peeps['age'] > 35) | (peeps['last_name'] == 'Winter')

In [84]:
peeps[filt_age]

         first_name last_name  age
initials
JKM            John     Marsh   58
DEM           Diane    McCabe   60

In [164]:
peeps.loc[filt_age | filt_name]

  initials first_name last_name  age
1      JKM       John     Marsh   58
2      RLW    Rebecca    Winter   27
3      DEM      Diane    McCabe   60

In [166]:
peeps.loc[filt_all]

  initials first_name last_name  age
1      JKM       John     Marsh   58
2      RLW    Rebecca    Winter   27
3      DEM      Diane    McCabe   60

In [85]:
peeps.loc[~filt_age]

         first_name last_name  age
initials
JDH          Joshua    Harvey   31
RLW         Rebecca    Winter   27

In [175]:
pd.set_option('display.max_columns',30)

In [176]:
df['ConvertedComp'].value_counts()

2000000.0    709
1000000.0    558
120000.0     502
100000.0     480
150000.0     434
            ...
52826.0        1
72888.0        1
7548.0         1
20436.0        1
44947.0        1
Name: ConvertedComp, Length: 9162, dtype: int64

In [198]:
countries = ['United States', 'Canada', 'Germany']

In [210]:
filt_salary = (df['ConvertedComp'] > 150000)
filt_country = (df['Country'].isin(countries))
filt_dialect = (df['LanguageWorkedWith'].str.contains('Python', na=False))
filts = filt_salary & filt_country & filt_dialect

In [211]:
df.loc[filts, ['Country','LanguageWorkedWith', 'ConvertedComp']]

,Country,LanguageWorkedWith,ConvertedComp
31,United States,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,1100000.0
44,United States,Python,175000.0
105,United States,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,160000.0
260,United States,C++;C#;HTML/CSS;Java;JavaScript;PHP;Python;SQL...,864000.0
310,United States,Bash/Shell/PowerShell;Python;Ruby;SQL,160000.0
...,...,...,...
88164,Canada,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,732852.0
88244,United States,Bash/Shell/PowerShell;Go;Python;Ruby,225000.0
88264,United States,HTML/CSS;Java;JavaScript;Kotlin;Python;SQL,2000000.0
88321,United States,C++;Python;Scala;SQL,2000000.0
88323,United States,Bash/Shell/PowerShell;C#;HTML/CSS;Java;Python;...,180000.0

In [220]:
df['Country'].str.istitle()

0         True
1        False
2         True
3         True
4         True
         ...
88878     True
88879      NaN
88880      NaN
88881      NaN
88882     True
Name: Country, Length: 88883, dtype: object

In [221]:
df['ConvertedComp'].max()

2000000.0